# Generated by Django 5.0.2 on 2024-02-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Madlib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('noun', models.CharField(max_length=50)),
                ('pronoun', models.CharField(max_length=50)),
                ('adjective', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('verb', models.CharField(max_length=50)),
            ],
        ),
    ]
