# Generated by Django 5.0.2 on 2024-02-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madlib_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='madlib',
            name='template_name',
            field=models.CharField(default='default_template.html', max_length=50),
        ),
    ]
